// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Modal': string;
  'ModalWrapper': string;
  'button': string;
  'modal': string;
  'modalWrapper': string;
  'themeLayerTable': string;
  'title': string;
  'title1': string;
  'title2': string;
}
declare var cssExports: CssExports;
export = cssExports;
