// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CEiLi': string;
  'activityImage': string;
  'activityType': string;
  'addButton': string;
  'addButtonContent': string;
  'bJrJHb': string;
  'box': string;
  'cEiLi': string;
  'content': string;
  'customloader': string;
  'customloaderParent': string;
  'dDJIOg': string;
  'dDjiOg': string;
  'deleteBtn': string;
  'fileUploadBtn': string;
  'gGAqlL': string;
  'h1': string;
  'h2': string;
  'historyBox': string;
  'iZHiCE': string;
  'iZHiCe': string;
  'load5': string;
  'nav': string;
  'registerBtn': string;
  'upload': string;
  'upload1': string;
  'upload2': string;
  'upload3': string;
  'upload4': string;
  'zShangchuan': string;
  'z_shangchuan': string;
}
declare var cssExports: CssExports;
export = cssExports;
