// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activityImage': string;
  'addButton': string;
  'addButtonContent': string;
  'box': string;
  'content': string;
  'customloader': string;
  'customloaderParent': string;
  'deleteBtn': string;
  'fileUploadBtn': string;
  'historyBox': string;
  'load5': string;
  'nav': string;
  'registerBtn': string;
}
declare var cssExports: CssExports;
export = cssExports;
