// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'LoginModal': string;
  'LoginModalWrapper': string;
  'h1': string;
  'input': string;
  'jCqlPJ': string;
  'jCqlPj': string;
  'kAhQEk': string;
  'li': string;
  'loginModal': string;
  'loginModalWrapper': string;
  'yj': string;
  'zLogin': string;
  'z_login': string;
}
declare var cssExports: CssExports;
export = cssExports;
