// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CEiLi': string;
  'OKQLs': string;
  'cEiLi': string;
  'eRJlwo': string;
  'egvBvY': string;
  'gZBeA': string;
  'kbEUjn': string;
  'okqLs': string;
  'zJiansuo': string;
  'zOkqLs': string;
  'z_OKQLs': string;
  'z_jiansuo': string;
}
declare var cssExports: CssExports;
export = cssExports;
