// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back-button': string;
  'back-button-white': string;
  'back-button1': string;
  'backButton': string;
  'backButton1': string;
  'backButtonWhite': string;
  'complexHeader': string;
  'custom-checkbox': string;
  'custom-feature-info-panel': string;
  'custom-hover-row': string;
  'custom-radio': string;
  'customCheckbox': string;
  'customFeatureInfoPanel': string;
  'customHoverRow': string;
  'customRadio': string;
  'main-content': string;
  'mainContent': string;
  'radio-label': string;
  'radioLabel': string;
  'save-button': string;
  'saveButton': string;
  'theme-item': string;
  'themeItem': string;
  'tjs-feature-info-panel__body': string;
  'tjs-standard-user-interface__ui-root': string;
  'tjsFeatureInfoPanelBody': string;
  'tjsStandardUserInterfaceUiRoot': string;
  'zBackButton': string;
  'zLi': string;
  'zTable': string;
  'z_backButton': string;
  'z_li': string;
  'z_table': string;
}
declare var cssExports: CssExports;
export = cssExports;
