// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CEiLi': string;
  'OKQLs': string;
  'cEiLi': string;
  'egvBvY': string;
  'gZBeA': string;
  'okqLs': string;
  'zJingluo': string;
  'z_jingluo': string;
}
declare var cssExports: CssExports;
export = cssExports;
