// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg': string;
  'loginBtn': string;
  'logoutBtn': string;
}
declare var cssExports: CssExports;
export = cssExports;
