// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'CEiLi': string;
  'OKQLs': string;
  'cEiLi': string;
  'content': string;
  'okqLs': string;
  'raw-data-button': string;
  'rawDataButton': string;
  'section': string;
  'time-series-chart': string;
  'timeSeriesChart': string;
  'title': string;
  'zTable': string;
  'z_table': string;
}
declare var cssExports: CssExports;
export = cssExports;
