// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Modal': string;
  'ModalWrapper': string;
  'modal': string;
  'modalWrapper': string;
  'title': string;
  'zButton1': string;
  'zButton2': string;
  'zTable': string;
  'z_button1': string;
  'z_button2': string;
  'z_table': string;
}
declare var cssExports: CssExports;
export = cssExports;
