// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'img': string;
  'themeLayerTable': string;
  'themeLayerTable1': string;
  'themeLayerTable2': string;
  'title': string;
  'title1': string;
  'zButton1': string;
  'zButton2': string;
  'zSelect': string;
  'z_button1': string;
  'z_button2': string;
  'z_select': string;
}
declare var cssExports: CssExports;
export = cssExports;
