insert into public.graph_list_template_settings(item_id,graph_type_id,attribute_name,attribute_type,display_name,display_type,group_type,placeholder_flag) values 
    (1,1,'rodYColumnName',1,'(複合)棒グラフ Y軸 カラム名',1,null,'0')
  , (2,1,'xColumnName',1,'(複合)X軸 カラム名',1,null,'0')
  , (3,1,'lineYColumnName',1,'(複合)折れ線グラフ Y軸 カラム名',1,null,'0')
  , (4,1,'rodYMax',2,'(複合)棒グラフ Y軸最大値',1,null,'0')
  , (5,1,'rodYMin',2,'(複合)棒グラフ Y軸最最小値',1,null,'0')
  , (6,1,'lineYMax',2,'(複合)折れ線グラフ Y軸最大値',1,null,'0')
  , (7,1,'lineYMin',2,'(複合)折れ線グラフ Y軸最小値',1,null,'0')
  , (8,1,'rodYStepSize',2,'(複合)棒グラフ Y軸ステップサイズ',1,null,'0')
  , (9,1,'lineYStepSize',2,'(複合)折れ線グラフ Y軸ステップサイズ',1,null,'0')
  , (10,1,'rodYUnit',2,'(複合)棒グラフ Y軸単位',1,null,'0')
  , (11,1,'lineYUnit',2,'(複合)折れ線グラフ Y軸単位',1,null,'0')
  , (12,1,'rodBackGroundColor',1,'(複合)棒グラフ 背景色',2,null,'0')
  , (13,1,'lineBackGroundColor',1,'(複合)折れ線グラフ 背景色',2,null,'0')
  , (14,1,'rodBorderColor',1,'(複合)棒グラフ 線色',2,null,'0')
  , (15,1,'lineBorderColor',1,'(複合)折れ線グラフ 線色',2,null,'0')
  , (16,1,'lineYLabel',1,'(複合)折れ線グラフ Y軸ラベル',1,null,'0')
  , (17,1,'rodYLabel',1,'(複合)棒グラフ Y軸ラベル',1,null,'0')
  , (18,1,'xLabel',1,'(複合)X軸 ラベル',1,null,'0')
  , (1,2,'dataColumnName',1,'円グラフ データ カラム名',1,null,'0')
  , (2,2,'labelColumnName',1,'円グラフ ラベル カラム名',1,null,'0')
  , (3,2,'dataUnit',1,'円グラフ データ 単位',1,null,'0')
  , (4,2,'backgroundColorList',3,'円グラフ 背景色一覧',2,null,'0')
  , (5,2,'labelColorList',5,'円グラフ ラベル背景色対応一覧',4,null,'0')
  , (100,2,'$YColumnPlaceHoderName$',1,'円グラフ データ SQLプレースホルダ名',1,null,'1')
  , (101,2,'$XColumnPlaceHoderName$',1,'円グラフ ラベル SQLプレースホルダ名',1,null,'1')
  , (102,2,'$TablePlaceHoderName$',1,'円グラフ テーブル SQLプレースホルダ名',1,null,'1')
  , (1,3,'rodYColumnName',1,'棒グラフ Y軸 カラム名',1,null,'0')
  , (2,3,'xColumnName',1,'棒グラフ X軸 カラム名',1,null,'0')
  , (3,3,'rodYMax',2,'棒グラフ Y軸最大値',1,null,'0')
  , (4,3,'rodYMin',2,'棒グラフ Y軸最最小値',1,null,'0')
  , (5,3,'rodYStepSize',2,'棒グラフ Y軸ステップサイズ',1,null,'0')
  , (6,3,'rodYUnit',2,'棒グラフ Y軸単位',1,null,'0')
  , (7,3,'rodBackGroundColor',1,'棒グラフ 背景色',2,null,'0')
  , (8,3,'rodBorderColor',1,'棒グラフ 線色',2,null,'0')
  , (9,3,'rodYLabel',1,'棒グラフ Y軸ラベル',1,null,'0')
  , (10,3,'xLabel',1,'棒グラフ X軸 ラベル',1,null,'0')
  , (11,3,'direction',1,'棒グラフ 方向(縦：vertical or 横：horizontal )',1,null,'0')
  , (12,3,'subLabelColumnName',1,'棒グラフ サブラベル　カラム名',1,null,'0')
  , (13,3,'stackFlag',1,'棒グラフ 積み立て表示フラグ(有効：1 or 無効：0)',1,null,'0')
  , (100,3,'$YColumnPlaceHoderName$',1,'棒グラフ Y軸 SQLプレースホルダ名',1,null,'1')
  , (101,3,'$XColumnPlaceHoderName$',1,'棒グラフ X軸 SQLプレースホルダ名',1,null,'1')
  , (102,3,'$TablePlaceHoderName$',1,'棒グラフ テーブル SQLプレースホルダ名',1,null,'1')
  , (1,4,'lineYColumnName',1,'線グラフ Y軸 カラム名',1,null,'0')
  , (2,4,'xColumnName',1,'線グラフ X軸 カラム名',1,null,'0')
  , (3,4,'lineYMax',2,'線グラフ Y軸最大値',1,null,'0')
  , (4,4,'lineYMin',2,'線グラフ Y軸最最小値',1,null,'0')
  , (5,4,'lineYStepSize',2,'線グラフ Y軸ステップサイズ',1,null,'0')
  , (6,4,'lineYUnit',2,'線グラフ Y軸単位',1,null,'0')
  , (7,4,'lineBackGroundColor',1,'線グラフ 背景色',2,null,'0')
  , (8,4,'lineBorderColor',1,'線グラフ 線色',2,null,'0')
  , (9,4,'lineYLabel',1,'線グラフ Y軸 ラベル',1,null,'0')
  , (10,4,'xLabel',1,'線グラフ X軸 ラベル',1,null,'0')
  , (100,4,'$YColumnPlaceHoderName$',1,'線グラフ Y軸 SQLプレースホルダ名',1,null,'1')
  , (101,4,'$XColumnPlaceHoderName$',1,'線グラフ X軸 SQLプレースホルダ名',1,null,'1')
  , (102,4,'$TablePlaceHoderName$',1,'線グラフ テーブル SQLプレースホルダ名',1,null,'1')
  , (1,5,'selectType',1,'リスト選択オプション (single or multiple)',1,null,'0')
  , (2,5,'displayColumnNameList',5,'リスト対象カラム一覧',4,null,'0')
  , (3,5,'linkColumnNameList',5,'リンク対象カラム一覧',4,null,'0')
  , (4,5,'flexColumnWidth',2,'列幅の自動調整(有効：1 or 無効：0)',1,null,'0')
  , (5,5,'groupColumnName',1,'リストグループカラム名',1,null,'0')
  , (6,5,'groupTotalColumnName',1,'リストグループ合計値カラム名',1,null,'0')
  , (100,5,'$ColumnListPlaceHoderName$',1,'リスト カラム一覧 SQLプレースホルダ名',1,null,'1')
  , (102,5,'$TablePlaceHoderName$',1,'リスト テーブル SQLプレースホルダ名',1,null,'1')
  , (1,6,'displayColumnName',1,'単一リスト表示カラム',1,null,'0');
