// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'helpBtn': string;
  'helpBtnSelected': string;
}
declare var cssExports: CssExports;
export = cssExports;
