// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'li-active': string;
  'liActive': string;
  'logo': string;
  'main-content': string;
  'mainContent': string;
  'menu-ul': string;
  'menuUl': string;
  'sample-icon': string;
  'sample-logout': string;
  'sample-logout-icon': string;
  'sampleIcon': string;
  'sampleLogout': string;
  'sampleLogoutIcon': string;
  'side-bar': string;
  'sideBar': string;
  'zBg': string;
  'zHead': string;
  'z_bg': string;
  'z_head': string;
}
declare var cssExports: CssExports;
export = cssExports;
