// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'originalGradient': string;
  'panel': string;
  'panelWrapper': string;
  'yj': string;
  'zButton': string;
  'zH1': string;
  'zInput': string;
  'zTitle': string;
  'z_button': string;
  'z_h1': string;
  'z_input': string;
  'z_title': string;
}
declare var cssExports: CssExports;
export = cssExports;
