// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'allDisplayBtn': string;
  'eYbMCg': string;
  'explorerPanelIsVisible': string;
  'featureInfo': string;
  'featureInfoFullScreen': string;
  'feedback': string;
  'fiuEyn': string;
  'fullViewerGrid': string;
  'mainLeftGrid': string;
  'mainRightGrid': string;
  'map': string;
  'showWorkbenchButton': string;
  'showWorkbenchButtonTrainerBarVisible': string;
  'showWorkbenchButtonisNotVisible': string;
  'showWorkbenchButtonisVisible': string;
  'sidePanel': string;
  'sidePanelHide': string;
  'story-wrapper': string;
  'storyWrapper': string;
  'ui': string;
  'ui-root': string;
  'uiInner': string;
  'uiRoot': string;
  'zGuanbi': string;
  'zJianzhu': string;
  'z_guanbi': string;
  'z_jianzhu': string;
}
declare var cssExports: CssExports;
export = cssExports;
