// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bbZcMN': string;
  'bbZcMn': string;
  'btn': string;
  'button': string;
  'flex': string;
  'langBtn': string;
  'menu': string;
  'menu-bar': string;
  'menu-item': string;
  'menuBar': string;
  'menuBtn': string;
  'menuItem': string;
  'theme-item': string;
  'themeItem': string;
  'zAnniu': string;
  'zAnniuMob': string;
  'zBg': string;
  'zButton': string;
  'zSelect': string;
  'z_anniu': string;
  'z_anniu_mob': string;
  'z_bg': string;
  'z_button': string;
  'z_select': string;
}
declare var cssExports: CssExports;
export = cssExports;
